# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD:admin123
    volumes:
      - mysql:/docker-entrypoint-initdb.d
      
  services1:
    image: springio/demo
    links:
      - db
    restart: always
    expose:
      - 8080
    
  services2:
    image: springio/demo
    links:
      - db
    restart: always
    expose:
      - 8080
    
  nginx:
    image: nginx:stable
    links:
      - services1
      - services2
    ports:
      - 8000:80
    volumes:
      - nginx:/etc/nginx/conf.d
    
    