# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_DATABASE=springlibrary
      - MYSQL_USER=melody
      - MYSQL_PASSWORD=123456
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    expose:
      - 3306
      
  service1:
    image: springio/demo
    links:
      - db
    restart: always
    expose:
      - 8080
    
  service2:
    image: springio/demo
    links:
      - db
    restart: always
    expose:
      - 8080
    
  nginx:
    image: nginx:stable
    links:
      - service1
      - service2
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    
    